Update es.json
GTAKoth/translations pull request #16
Opened 2023-02-27 21:34 UTC by FroggySVJ

2023-02-27 21:37 UTC, FroggySVJ commented
Full made es.json 
Native language without translators

**Froggy__#0365**

2023-03-01 10:49 UTC, JackCosens requested changes

2023-03-01 10:49 UTC, JackCosens commented on es.json
> +        "squad-player-not-in-squad": "El jugador [% s] no está en tu escuadron",
Malformed wont work on production server - please correct to [%s] then good for merge.

2023-11-29 09:44 UTC, AxPeRxX commented
Updated es.json 
Actual spanish from spain, includes accent marks 🇪🇸
[es.json](https://github.com/GTAKoth/translations/files/13498764/es.json)

2024-05-28 21:43 UTC, closed without merging